config/routes.rb
Dateikit::Application.routes.draw do
  resources :downloads, except: [:show, :new, :create] do
    member do
      get 'download'
    end
  end

  match '/f/:filename' => 'downloads#download',
    constraints: { filename: /.*/ }, via: :get

  root "static#home"

end

app/models/download.rb
class Download < ActiveRecord::Base

  MAX_DOWNLOAD_COUNT = ENV["MAX_DOWNLOAD_COUNT"] || 1
  AUTO_DELETE_AFTER = ENV["AUTO_DELETE_AFTER"] || 5

  validates :filename, :download_count, :allowed_downloads, presence: true
  validates :filename, uniqueness: true
  validates :allowed_downloads, numericality: {greater_than: 0, less_than: 100000}

  before_validation :set_initial_values, on: :create

  def self.filename_or_id(filename: nil, id: nil)
    return unless :filename && :id
    return find(id) if id
    find_database_and_local_files(filename)
  end

  def self.find_database_and_local_files(filename)
    file = find_by_filename(filename)
    return file if file
    file_list = get_list_of_files
    return unless file_list
    exists_locally = get_list_of_files.include?(filename)
    return unless exists_locally
    create(filename: filename)
  end

  def self.get_list_of_files
    begin
      Dir.glob("public/files/*").map{|file_and_path| file_and_path.split("/").last}
    rescue
      nil
    end
  end

  def path
    "public/files/#{filename}"
  end

  def send_update_download
    self.download_count += 1
    save
    path
  end

  def allowed_to_download?
    download_count < allowed_downloads
  end

  def should_destroy?
    download_count >= allowed_downloads || Time.now >= expires_at
  end

  private

  def set_initial_values
    self.download_count = 0
    self.allowed_downloads = MAX_DOWNLOAD_COUNT
    self.expires_at = Time.now + AUTO_DELETE_AFTER.days
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_auth_token
  before_filter :check_auth_token

  def set_auth_token
    if params[:token]
      cookies[:token] = params[:token]
    end
  end

  def check_auth_token
    if cookies[:token] != ENV["SECRET_KEY_MANAGE_FILES"]
      flash[:error] = "You shall not pass"
      redirect_to root_path
      false
    end
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController

  before_action :set_download, only: [:show, :edit, :update, :destroy]

  skip_before_filter :check_auth_token, only: [:download]

  # GET /downloads
  def index
    @downloads = Download.all.order('created_at DESC')
  end

  # GET /downloads/1
  def show
  end

  # GET /downloads/new
  def new
    @download = Download.new
  end

  # GET /downloads/1/edit
  def edit
  end

  # POST /downloads
  def create
    @download = Download.new(download_params)

    if @download.save
      redirect_to @download, notice: 'Download was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /downloads/1
  def update
    if @download.update(download_params)
      redirect_to downloads_path, notice: 'Download was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /downloads/1
  def destroy
    @download.destroy
    redirect_to downloads_url, notice: 'Download was successfully destroyed.'
  end

  def download
    @download = Download.filename_or_id(filename: params[:filename], id: params[:id])
    if @download && @download.allowed_to_download?
      send_file @download.send_update_download
    else
      raise ActionController::RoutingError.new('File could not be found or has been deleted.')
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_download
    @download = Download.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def download_params
    params.require(:download).permit(:allowed_downloads, :expires_at)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_filter :check_auth_token

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def whitespace(item)
    " #{item}"
  end

  def with_x(number)
    "#{number}x"
  end

  def notices?
    flash[:notice] || flash[:alert] || flash[:error]
  end

end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/views/downloads/_form.html.slim
= simple_form_for @download do |f|
  = f.input :allowed_downloads
  = f.input :expires_at
  .form-actions
    = f.button :submit

app/views/downloads/edit.html.slim
h1 Editing download

== render 'form'

app/views/downloads/index.html.slim
h3 Available downloads
table.table.table-bordered.table-controls.table-striped
  tr
    th Filename
    th Download count
    th Allowed downloads
    th Expires at
    th Short url
    th Controls

  - @downloads.each do |download|
    tr
      td= link_to download.filename, download_download_path(download)
      td= with_x download.download_count
      td= download.allowed_downloads
      td= download.expires_at
      td= download.short_url
      td
        .btn-group
          = link_to download_download_path(download), class: "btn" do
            i.icon-download
            = whitespace 'Download'
          = link_to edit_download_path(download), class: "btn" do
            i.icon-edit
            = whitespace 'Edit'
          = link_to download, class: "btn", data: { confirm: "Deletion can not be undone" },
            :method => :delete do
            i.icon-remove
            = whitespace 'Remove'

app/views/downloads/new.html.slim
h1 New download

== render 'form'

= link_to 'Back', downloads_path

app/views/downloads/show.html.slim
p#notice = notice

p
  strong Download count:
  = @download.download_count
p
  strong Allowed downloads:
  = @download.allowed_downloads
p
  strong Expires at:
  = @download.expires_at
p
  strong Short url:
  = @download.short_url

= link_to 'Edit', edit_download_path(@download)
'|
= link_to 'Back', downloads_path

app/views/layouts/_notices.html.slim
- if notices?
  .notices
    - if flash[:notice]
      .alert.alert-success
        a.close data-dismiss="alert" ×
        = flash[:notice]
    - if flash[:alert]
      .alert.alert-error
        a.close data-dismiss="alert" ×
        = flash[:alert]
    - if flash[:error]
      .alert.alert-error
        a.close data-dismiss="alert" ×
        = flash[:error]

app/views/layouts/application.html.slim
doctype html
html
  head
    title= "Datekit"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'

    = csrf_meta_tags

  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to downloads_path, class: "brand" do
            i.icon-file
            span DATEIKIT


    .container#main-container
      .row
        .span12
          = render "layouts/notices"
          = yield